@startuml
'https://plantuml.com/sequence-diagram

'Systems'
package DungeonWarrior 
{
    package ENUMS
    {
        enum CollisionTypes 
        {
            PLAYER
            WALL
            FLOOR
        }
    }

    class Game 
    {
        Initialize SDL
        Initialize managers
    }
    
    package Player
    {
        class PlayerManager 
        {
            Setup player
            Return player reference
        }
    }
    
    package Input 
    {
        class InputManager
        {
            Check if input is valid
            Receive inputs from SDL
        }
    }
    
    package Map
    {
        class MapManager
        {
            create maps using tiles 
        }
        
        class Tile 
        {
            a small part of the map
        }
    }
    
    package Core 
    {
        package Sprite
        {
            class SpriteManager
            {
                create and return sprites
            }
            
            class Sprite
            {
                
            }
        }
        
        package Transform
        {
            class TransformManager
            {
                create and return transforms
            }
            
            class Transform
            {
                
            }
        }
        
        package Utils
        {
            class Vector2
            {
                
            }
        }
    }
}


@enduml